[package]
name = "xtask"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.209", features = ["derive"] }
toml = "0.8.19"
xshell = "0.2.6"
week_calendar = { path = "../" }
clap = "4.5.16"
cargo_toml = "0.20.4"
