name: "Format check, Clippy and unit tests in rust" 
on: 
  push: 
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:  
    branches:
      - main
    paths-ignore:
      - '**.md'
        
jobs:
  checks_via_just:
    name: "Check formating, linting, unit tests and spelling"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: extractions/setup-just@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: just ci
