
name: "Spelling" 
on: 
  push: 
    branches: [ $default-branch ]
    paths-ignore:
      - '**.md'
  pull_request:  
    branches: [ $default-branch ]
    paths-ignore:
      - '**.md'

jobs:
  spelling:
    name: "Checking via typos"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: crate-ci/typos@master 
